# ==============================================================================
#  [Ziggurat OS] HIGH-PERFORMANCE DOCUMENT SERVICE UPSTREAM MATRIX (v2335)
#  Path: layers/services/ds/.ziggurat/.infrastructure/.nginx/.upstreams/ds.conf
# ==============================================================================
upstream ds_backend {
    server ${ZOS_SDN_GATEWAY}:${DS_PORT};
}
